### PR TITLE
1.2.0.0

### PR DESCRIPTION
**Pull request by bworrell**
Adds support for STIX v1.2

**TODO**: Bump the `__version__` to `1.2.0.0` brefore tagging.

### CODE REVIEW

**Comment by gtback** [comment]
The API coverage documentation for vocabs doesn't seem to be entirely working since none of the versioned (`X_1_0`) vocabs are documented. The only ones defined are the aliases, which don't show the actual terms in the Vocab. Also, somehow `AvailabilityLossTypeVocab-1.0` got linked to `stix.common.vocabs.AttackToolType_1_0` which I don't think exists, and even if so, is not right. :smile:

**Comment by bworrell** [comment]
@gtback, good catch! I think I fixed the issues you mentioned.

**Comment by gtback** [comment]
I think this is fine to merge after the actual STIX 1.2 release.

**Comment by bworrell** [comment]
@gtback, thanks for looking at this! I'm gonna merge it now :)

**Pull request merged**
