### PR TITLE
CIQ Identity updates

### PR DESCRIPTION
**Pull request by gtback**
Add the changes from the stix1.1.1 branch to master.

### CODE REVIEW

**Comment by gtback** [comment]
@emmanvg, can you look at this and see if I missed anything obvious. Otherwise, if the build passes, can you go ahead and merge?

**Comment by emmanvg** [comment]
The CIQ tests are passing, but I receive an error on: [https://github.com/STIXProject/python-stix/blob/ciq-updates/stix/test/indicator_test.py#L460](url)

**Comment by emmanvg** [comment]
Never mind, it might be a problem on my side. Travis seems to find no conflicts. We should be all set.

**Comment by gtback** [comment]
Thanks! I couldn't get that test to fail; you had me worried ;-)

**Pull request merged**
