### PR TITLE
Handle CIQ Identities correctly

### LINKED ISSUE #302: CIQ objects do not seem to be handled correctly in 1.2.0.1
When I updated to 1.2.0.1, the CIQ details in the Identity object were missing.

### PR DESCRIPTION
**Pull request by gtback**
Fix #302

### CODE REVIEW

**Comment by gtback** [comment]
@clenk , @rpiazza : Can one of you take a look at this and merge if it fixes the problems you were having, and the CI build passes?

**Comment by rpiazza** [comment]
Ran a test - that idiom is still wrong.

@emmanvg seems to think it is some issue with getting the xsi:type set.

**Comment by clenk** [comment]
My problem may be unrelated - STIXPackage.from_xml() isn't reading in the Identity correctly and just creates a \<ta:Identity/\> stub.

**Comment by clenk** [comment]
I believe my problem comes from [IdentityType.buildchildren()](https://github.com/STIXProject/python-stix/blob/40d89f0a24d38c02c68274f188d71d0866a6aece/stix/bindings/stix_common.py#L1358), which does nothing if the NodeName_ == "Specification" which is true for a CIQIdentity. Should we do something like [MalwareType.buildchildren()](https://github.com/STIXProject/python-stix/blob/40d89f0a24d38c02c68274f188d71d0866a6aece/stix/bindings/ttp.py#L776), which imports the proper extension module?

**Comment by emmanvg** [comment]
Just pushed some changes. It should be working now. :)

**Pull request merged**
