### PR TITLE
Fix for issue #274: STIXPackage.add() now correctly adds TTPs.

### PR DESCRIPTION
**Pull request by chisholm**

### CODE REVIEW

**Comment by bworrell** [comment]
@chisholm, can you write a unit test for the `add()` method?

**Comment by chisholm** [comment]
I started doing this, and ran into an oddity with the STIXPackage class.  All of the entitylist properties on it except `observables` will create an empty list when the property is set to None.  So default-constructing a STIXPackage results in all of the entitylist properties being initialized to empty lists, except the observables property, which is initialized to None.

The style of code is different for that property: the setter does _set_var(), whereas the others just directly instantiate an entitylist.  Why the inconsistency?  (It caused an error in my code... which I can work around, but why work around when you can fix?)

**Comment by bworrell** [comment]
@chisholm, 

I don't know if there is a reason for the inconsistency. I think we want users to be able to `append()` after instantiating a `STIXPackage` object:

```python
package = STIXPackage()
package.indicators.append(my_indicator)
``
...which is why the `EntityList` property setters work that way. 

Maybe they should just be created in the `__init__()` method and the property setters allow users to set a field to `None` (like `observables`). What do you think?

We can default `observables` to an empty `Observables` object in `__init__()` as well, but it may need special handling in `to_dict()` and `to_obj()` since I don't know if it has the same `__nonzero__()` behavior (actually, after looking at its code I think its inherited `EntityList.__nonzero__()` may produce incorrect results). You'll probably need to check its `len()` and if it has an `observable_package_source` set inside `STIXPackage.to_dict()|to_obj()` before attempting to call `to_obj()` or `to_dict()` on it. Otherwise you'll export an empty `stix:Observables` element with version attributes set every time.

Write the tests and update the code to work the way you'd expect but don't get too hung up on the implementation. The `typedfields` branch is going to be merged into `master` eventually so `STIXPackage` is going to look pretty different in a bit. But we'd still want those tests to pass after merge.

I don't know if I actually answered your question ;)

**Comment by gtback** [comment]
@chisholm, I'm going to merge this. If you think there's something else that needs to be done, please open a new issue.

**Pull request merged**
