### PR TITLE
add decep extension

### PR DESCRIPTION
**Pull request by bschmoker**
@bworrell  - does this look good?

### CODE REVIEW

**Comment by gtback** [comment]
Empty commit? I'm confused. I'm guessing this is still a work in progress?

**Comment by bschmoker** [comment]
@gtback #wip https://github.com/STIXProject/schemas/pull/334#issuecomment-108102856

**Comment by gtback** [comment]
`deception` isn't an extension point. Would it make sense for this to go somewhere else? We don't really have a place for "custom vocabs", since they are, by definition, custom.

**Comment by johnwunder** [comment]
IMO this shouldn't be integrated into `python-stix` until the community discusses it and it gets added to STIX.

**Comment by bworrell** [comment]
@gtback, the extension part comes from the `schemas` PR that @bschmoker made. I agree with @johnwunder; we should wait until it makes its way into a release before merging it into the codebase.

**Comment by gtback** [comment]
In that case, any objections to closing the PR but leaving the branch?

**Comment by bschmoker** [comment]
@gtback - would lean towards keeping open, since it'll act as a reminder 
(and a stale branch will fall into obscurity)

**Comment by gtback** [comment]
Closing in the interest of cleanup.

**Pull request closed without merging**
