### PR TITLE
blow away that header #deprecated

### PR DESCRIPTION
**Pull request by bschmoker**

### CODE REVIEW

**Comment by bworrell** [comment]
Thanks @bschmoker! I'm gonna merge this now.

**Comment by bschmoker** [comment]
@bworrell does landscape do some kind of build checks btw? 
I assume that it calculates health based on some kind of auto-build thingie

**Comment by bworrell** [comment]
From what I can tell, landscape runs `pyflakes`, `pylint`, `pep8` and some other homebrew stuff against your repository when commits are pushed and then derives a score from the reports. The landscape-bot messages come in on PRs and are updated with new commits to PRs. I sorta love it.

**Comment by bworrell** [comment]
I guess this is their inspection tool: https://github.com/landscapeio/prospector

**Comment by gtback** [comment]
Yes, prospector is their code checker, based on pyflakes and other tools.

**Pull request merged**
