### PR TITLE
Fixes for STIX 1.1.1.X

### PR DESCRIPTION
**Pull request by emmanvg**

### CODE REVIEW

**Comment by gtback** [comment]
I added tests for #338 and #325, but counldn't figure out a good way to test how the library behaves when MAEC is not installed (except manually uninstalling it and running the tests, which doesn't work well with tox/travis).

**Comment by emmanvg** [comment]
Mmm... I will test with creating a new `testenv` and provide the `deps` except for MAEC and test. Since I still have an open issue for python-stix I can provide it in the next PR if I am successful at it. 👍

**Comment by gtback** [comment]
The tricky part is specifying which tests to run when maec is installed and when it isn't. I'll create a separate issue for this.

**Comment by emmanvg** [comment]
This should also resolve oasis-open/cti-stix-elevator#93 once the release is made.

**Pull request merged**
